name: Auto-create Issues on Milestone Creation

on:
  milestone:
    types: [created]

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issues for New Milestone
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const milestoneTitle = context.payload.milestone.title;
            const milestoneNumber = context.payload.milestone.number;
            const repo = context.repo;

            // Define the issues to create
            const issues = [
              {
                title: "Content Ingestion",
                body: "Crawl and scrape the website, enrich with vectors (and any other required metadata, such as keywords)"
              },
              {
                title: "Validate Keyword Spreadsheet",
                body: `Check whether the keyword spreadsheet is in the right format, which can be one of the following:"
- list of client's target keywords in one column
- list of target keywords in one column, with a list of target urls (from own site) in another column (i.e. the page(s) they optimized to try to rank for the target keyword)
- real search engine keywords in one column (e.g. from Google Analytics), with landing URLs in another column, optionally with additional columns such as clicks or impressions
- no file. In this case, we will index the content on the site and synthesize questions that are answered by the pages on the site
`
              },
              {
                title: "Generate Synthetic Queries",
                body: "Based on keywords list in the previous step (i.e. issue)"
              },
              {
                title: "Create Snippets",
                body: "Create the snippets based on the queries (previous step)"
              },
              {
                title: "Process Queries for GEO Dashboard",
                body: "Process the queries on the platform (Staging) and schedule weekly “checkpoints” (on Prod) for reprocessing"
              },
              {
                title: "BigQuery Sync",
                body: "Copy the BQ Staging data to Prod for the client data"
              },
              {
                title: "User Credentials",
                body: "Give user credentials to commercial team to distibute to client users"
              }
            ];

            // Create issues and add to the milestone
            for (const issue of issues) {
              await github.rest.issues.create({
                ...repo,
                title: issue.title,
                body: issue.body,
                milestone: milestoneNumber
              });
            }
