name: Format Code on PR Merge

on:
  push:
    branches:
    - main

permissions:
  contents: write
  pull-requests: write

jobs:
  apply-formatting-and-open-pr:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: 17
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Install Black
        run: pip install black

      - name: Run Black on Python files
        run: black .
        working-directory: ./geo_backend

      - name: Run Prettier on JS files
        run: npx prettier --write "**/*.js"
        working-directory: ./geo_frontend

      - name: Check for changes
        id: changes
        run: |
          git config --global user.name "elelem-bot"
          git config --global user.email "github.bot@elelem.ai"
          if [[ -n $(git status --porcelain) ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR with formatting changes
        if: steps.changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git checkout -b apply-formatting-to-pr-${PR_NUMBER}
          git add .
          git commit -m "Apply code formatting with Black and Prettier"
          git push --set-upstream https://github.com/${{ github.repository }} apply-formatting-to-pr-${PR_NUMBER}
          gh pr create \
            --title "Code formatting after #${PR_NUMBER} merge" \
            --body "Applied Black (Python) and Prettier (JavaScript) formatting after PR merge to main." \
            --head apply-formatting-to-pr-${PR_NUMBER} \
            --base main
        shell: bash
